import { KTX0002 } from './KTX0002';
import { KTX0001 } from './KTX0001';
import { MKV9999 } from 'src/app/Models/MKV9999';
import { KTX0021 } from './KTX0021';
import { KTX0031 } from './KTX0031';
import { KTX0022 } from './KTX0022';
import { valuesearch } from './valuesearch';

export class KTX0020{
    public  KTX0020_ID  :number      ;
    public  MKV9999_ID  :number      ;
    public  okitucxa  :  boolean    ;
    public  ngayokitucxa  :string      ;
    public  quaylaikytucxa  :boolean      ;
    public  ngayquaylaikytucxa  :  string    ;
    public  thoigiantralantruoc  :string      ;
    public  lydodangkyoktx  :  string    ;
    public  nguyenvongophongso  :string      ;
    public  lydonguyenvong  : string     ;
    public  somayle  :string      ;
    public  didong   :string      ;
    public  nharieng  :  string    ;
    public  chunhiemnoilamviec  : boolean     ;
    public  truongphongnoilamviec  :  boolean    ;
    public  bqlktx  :    boolean  ;
    public  truongphongGA  :  boolean    ;
    public  KTX0001_ID  : number     ;
    public  KTX0002_ID  : number     ;
    public  KTX0003_ID  : number     ;
    public  printcount  : number     ;
    public  count  : number     ;
    public  khoaphong  : string     ;
    public  sotu  : string     ;
    public  sokhoatu  :  string    ;
    public  ngaycohieuluc  :  string    ;
    public  hotenbengiao  : string     ;
    public  bengiao  : boolean     ;
    public  bennhan  : boolean     ;
    public  hotenkhaisinh  : string     ;
    public  gioitinh  :   boolean   ;
    public  hotenkhac  :   string   ;
    public  ngaysinh  :string      ;
    public  noisinh  : string     ;
    public  quequan  :string      ;
    public  dantoc  : string     ;
    public  tongiao  :   string   ;
    public  cmtnd_so  : string     ;
    public  cmtnd_ngaycap  :string      ;
    public  cmtnd_noicap  :string      ;
    public  noithuongtru  : string     ;
    public  tienantoidanhhinhphat  : string     ;
    public  choohiennay  : string     ;
    public  trinhdohocvan  : string     ;
    public  trinhdchuyenmon  :string      ;
    public  biettiengdantocitnguoi  :string      ;
    public  bietngoaingu  :    string  ;
    public  nghenghiepchucvunoilam  :string      ;
    public  lamgiodautu14tuoi  : string     ;
    public  ngaytaodon  :string      ;
    public  ngayduyetdon  :string      ;
    public  noidung  :string      ;
    public  lydo  :string      ;
    public  ghichu  :string      ;
    public  trangthai  :boolean      ;
    public  check  :boolean      ;
    public  check2  :boolean      ;
    public  timkiem  :valuesearch      ;
    
   public   capbac:number;
    public   MKV9999  : MKV9999 =new MKV9999()    ;
    public   KTX0001  : KTX0001     ;
    public   KTX0002  : KTX0002     ;
    public   KTX0021  : KTX0021[]=[]     ;
    public   KTX0022  : KTX0022[]=[]     ;
    public   KTX0031  : KTX0031[]=[]     ;
    
}