export class MKV9999{
    public  MKV9999_ID :number     ;
    public  manhansu : string    ;
    public  matkhau :  string   ;
    public  id :  string   ;
    public  hodem : string    ;
    public  ten :  string   ;
    public  ngaysinh :Date     ;
    public  gioitinh :  boolean   ;
    public  noisinh : string    ;
    public  quequan : string    ;
    public  diachithuongtru :string     ;
    public  diachitamtru :  string   ;
    public  cmtnd_so :  string   ;
    public  cmtnd_ngayhethan :  Date   ;
    public  cmtnd_noicap :   string  ;
    public  hochieu_so :string     ;
    public  hochieu_ngaycap :Date     ;
    public  hochieu_ngayhethan :Date     ;
    public  ngayvaocongty : Date    ;
    public  phong_id : string    ;
    public  ban_id : string    ;
    public  congdoan_id :string     ;
    public  chucvu_id : string    ;
    public  nganhang_stk :  string   ;
    public  nganhang_id :  string   ;
    public  sosobaohiem : string    ;
    public  honnhantinhtrang : boolean    ;
    public  datnuoc_id :string     ;
    public  phuongxa : string    ;
    public  suckhoetinhtrang :string     ;
    public  dienthoai_nharieng :string     ;
    public  dienthoai_didong :  string   ;
    public  email :   string  ;
    public  tinhtrangnhansu : boolean    ;
    public  thutu : number    ;
    public  chucvu :string     ;
    public  capbac :  string   ;
    public  thetu_id :   string  ;
    // public virtual ICollection<MKV9980 MKV9980 :     ;
    // public virtual MKV9998 MKV9998 :     ;
}