import { RM0001 } from './RM0001';
import { RM0080 } from './RM0080';
import { RM0081_A } from './RM0081_A';
import { RM0081_B } from './RM0081_B';
import { RM0081_C, RM0081_D, RM0081_E, RM0081_F } from './RM0080_C';
export class RM0010{
    public  RM0010_ID :number    ;
    public  maID : string   ;
    public  HODEM : string   ;
    public  TEN : string   ;
    public  NGAYSINH : Date   ;
    public  NOISINH :string    ;
    public  CMTND_SO : string   ;
    public  CMTND_NGAYCAP :Date    ;
    public  CMTND_NOICAP :  string  ;
    public  GIOITINH :boolean    ;
    public  HONNHAN :boolean    ;
    public  TELEPHONE : string   ;
    public  MOBILE :  string  ;
    public  CHIEUCAO : string   ;
    public  CANNANG : string   ;
    public  EMAIL :string    ;
    public  THUONGTRU : string   ;
    public  TAMTRU :  string  ;
    public  RM0001_ID :string    ;
    public  RM0001_ID2 :string    ;
    public  NGAYCOTHELAM :Date    ;
    public THUNHAPMONGMUON :string    ;
    public  COTHELAMTHEM : boolean   ;
    public  COTHEDICONGTAC :boolean    ;
    public  COTHETHAYDOIDIADIEM :boolean    ;
    public  DATUNGTHITUYENMEIKO : boolean   ;
    public  NEUDATUNGTHITUYENMEIKO : string   ;
    public  ID_NGUONTHONGTIN :number    ;
    public  DUDINHTUONGLAI : string   ;
    public  SOTHICH : string   ;
    public  KHONGTHICH :string    ;
    public  CACPHAMCHATKYNANG :string    ;
    public  HOTENNGUOITHAN :string    ;
    public  DIACHINGUOITHAN :string    ;
    public  MOBILENGUOITHAN : string   ;
    public  ANHCHANDUNG : any   ;
    public  RM0011_ID1:string ;
    public  RM0011_ID2:string ;
    public  trangthai:boolean ;
    public  DUDINHHOCTIEPCHUYENNGANH:string ;
    public  bophanid:string ;
    public  DUDINHHOCTIEP:Boolean ;
    public  check:Boolean ;
    public  A0028_ID:string ;
    public  sophieu:number ;

    public i:number=0;
    public j:number=0;

    public  RM0001: RM0001     ;
    public  RM0080 :RM0080[]  =[]   ;
    public  RM0081_A :RM0081_A[]  =[]   ;
    public  RM0081_B : RM0081_B[] =[]   ;
    public  RM0081_C : RM0081_C[] =[]   ;
    public  RM0081_D :RM0081_D[]  =[]   ;
    public  RM0081_E :RM0081_E[] =[]    ;
    public  RM0081_F :RM0081_F[]=[]    ;
}